# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.network "public_network", bridge: [
    "en0: Wi-Fi (AirPort)",
  ]

  config.vm.synced_folder "../shared", "/vagrant_data", type: "nfs"

  config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/id_ed.pub", destination: "~/.ssh/authorized_keys"

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"

      # Certainly not the best way to handle this but, worked! ;-)
      if i == 1
        node.vm.network "private_network", ip: "192.168.34.10"
      else
        node.vm.network "private_network", ip: "192.168.34.11"
      end
    end
  end

  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  # end
end
