# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network", bridge: [
    "en0: Wi-Fi (AirPort)",
  ]

  config.vm.synced_folder "../shared", "/vagrant_data", type: "nfs"

  config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/id_ed.pub", destination: "~/.ssh/authorized_keys"
end
